language: python
env:
  - DB_URL=postgresql://postgres:postgres@localhost/priced-test
python:
  - "3.4"
  # PyPy versions
  # - "pypy"
  # - "pypy"  # PyPy2 2.5.0
  # - "pypy3" # Pypy3 2.4.0
  # - "pypy-5.3.1"
services:
  - postgres
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database priced-test;' -U postgres
# command to run tests
script: pytest ./test